### ISSUE TITLE
Stats button

### ISSUE THREAD

**Issue by romanoh** [hawkwynd/tesseract#3]
i think the stats button dont work: i have firefox.

![imagem](https://user-images.githubusercontent.com/5342223/95662224-442a7880-0b2d-11eb-878c-1676c0742a3e.png)

**Comment by Purwanto79** [comment]
In my case, all work on safari, chrome & firefox.

**Comment by romanoh** [comment]
its working now, weird, will do more tests, like leaving the window open, as it was to see.
