### ISSUE TITLE
Please some help

### ISSUE THREAD

**Issue by romanoh** [hawkwynd/tesseract#5]
The images don't appear.
The stats shows nothing.
The database don't populate.

![imagem](https://user-images.githubusercontent.com/5342223/95666536-80240480-0b52-11eb-9ee6-aa4f5aa3c9d3.png)

**Comment by hawkwynd** [comment]
Check the console log for errors. It displays alot of information in the browser's console log which may give you info on why you're not seeing the images and stats. Double check your config file to make sure you have your settings correct for the MYSQL connections.

**Comment by hawkwynd** [comment]
Nerdly stats are populated via ajax call, and modal is populated with results from mysql query. If your not getting results, check your mysql credentials in config.inc.php as you may not be properly connecting to your database. Did you import the .sql file located in the /mysql directory?

![image](https://user-images.githubusercontent.com/984241/95667241-bfd5f680-0b28-11eb-89fb-d41f6e4ea4f1.png)

**Comment by romanoh** [comment]
yes i upload the sql, and i have checked the credentials
this is my console:

![imagem](https://user-images.githubusercontent.com/5342223/95674055-aa52e200-0ba5-11eb-9ec2-ade8238203eb.png)

**Comment by Purwanto79** [comment]
My you must place all source code on web root folder. Or in my case, some little edit tessa2.js and keep.php.
All work fine & cool..

**Comment by romanoh** [comment]
Maybe thats the problem, i put all the folder tesseract in the root folder, and the paths were not changed. i will check.
