### ISSUE TITLE
Get metadata Artist from other

### ISSUE THREAD

**Issue by PoerOne** [hawkwynd/tesseract#6]
Hi Scott,
How can i get metadata artist from another country ?
I got nothing if artist from local country. And all successfully if music genre is Rock and international artist.

**Comment by hawkwynd** [comment]
The metadata is aquired from [discogs.com](https://www.discogs.com). If there is metadata from the artist you are requesting, it is retrieved. If not, you'll want to create an account with discogs.com and create the artist and metadata.
